<?php
declare(strict_types=1);

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Timoffmax\HomepageForm\ViewModel\HomepageForm $viewModel
 */
$viewModel = $block->getViewModel();
?>

<div data-bind="scope:'timoffmax-homepage-form'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Timoffmax_HomepageForm/js/dictionary/countries": {
                "list": <?= $viewModel->getCountriesJson() ?>
            },
            "Magento_Ui/js/core/app":  <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
         }
    }
</script>
